CREATE DATABASE dt48_mybatis CHARACTER SET utf8 COLLATE utf8_general_ci;
USE dt48_mybatis;
CREATE TABLE users(
	id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
	username VARCHAR(40) COMMENT '用户名',
	PASSWORD VARCHAR(40) COMMENT '密码'
)

SELECT * FROM users;---->LIST<USER>、List<Map<STRING,Object>>